server:
  port: 8089
  servlet:
    context-path: /swagger
spring:
  application:
    name: swagger
  datasource:
    url: jdbc:mysql://localhost:3306/recruit?useUnicode=true&characterEncoding=utf-8&useSSL=false
    password: root
    username: root
  rabbitmq:
    host: 127.0.0.1